---
- name: Install NGINX and copy index.html
  hosts: zkolyada
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: "Ansible the best"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

