---
- name: Install Docker on Ubuntu
  hosts: "{{ target_hosts }}"
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - lsb-release
          - python3-pip
          - python3-venv
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: latest
        update_cache: true

    - name: Create a virtual environment
      command: python3 -m venv /opt/venv

    - name: Install Docker Module for Python
      command: /opt/venv/bin/pip install docker
