---
- name: Execute 'ls /etc' and display output
  hosts: zkolyada
  gather_facts: no
  tasks:
    - name: Execute command to list /etc directory
      command: ls /etc
      register: etc_contents

    - name: Display output of ls /etc
      debug:
        msg: "{{ etc_contents.stdout }}"

